required("es")
module("es_shortcut")
es_shortcut.mb=es.MultiBlock
es_shortcut.rb=mb.Rigidbody
es_shortcut.tr=mb.Transform
es_shortcut.mod_block_type=mb.Type
es_shortcut.mod_block_uuid=mb.ModBlock.Uuid
es_shortcut.r=es.Root
es_shortcut.pl=es.Player
es_shortcut.q=es.Quaternion