required("es")
module("EvertechSandbox_shortcut")
mb=es.MultiBlock
rb=mb.Rigidbody
tr=mb.Transform
mbp=mb.Position
mbt=mb.Type
mbu=mb.ModBlock.Uuid
rbp=rb.Position
rbr=rb.Rotation
r=es.Root
pl=es.Player
cd=pl.CameraDirection
cp=pl.CameraPosition
q=es.Quaternion